# cloudbuild.yaml
steps:
  - name: node:18
    entrypoint: yarn
    args: ["install"]
  - name: node:18
    entrypoint: yarn
    args: ["run", "build"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY
